add links to sign up, login, logout forms to the main layout nav bar
altvec/task_manager pull request #14
Opened 2021-04-24 18:08 UTC by altvec

Смущает один момент. В [задании](https://learn.dualboot.ru/courses/5/lessons/76/practices/1146) для ссылки на регистрацию предлагается указать путь `new_developer_path`. Однако на [предыдущем уроке](https://learn.dualboot.ru/courses/5/lessons/76/practices/1145) мы писали роуты используя `developers`.

Как все-таки правильно делать? Думается, что в роутах должно быть `developer`...

2021-04-26 15:27 UTC, greybutton requested changes

2021-04-26 15:27 UTC, greybutton commented on app/views/layouts/application.html.slim
> +            = link_to "Sign up", new_developers_path, class: 'mdl-navigation__link'
запусти команду `rails routes` и посмотри какие пути доступны и выбери нужный. И желательно проверять что изменил код и работает ли он. В данном случае проверить открытие ссылок например

2021-04-27 05:59 UTC, altvec commented on app/views/layouts/application.html.slim
> +            = link_to "Sign up", new_developers_path, class: 'mdl-navigation__link'
В роутах *new_developers*:

```
bash-5.0# ./bin/rails routes -c web/developers
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.3-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
        Prefix Verb URI Pattern               Controller#Action
new_developers GET  /developers/new(.:format) web/developers#new
    developers POST /developers(.:format)     web/developers#create
```

ссылки все проверил - работают.

2021-04-27 07:39 UTC, greybutton commented on app/views/layouts/application.html.slim
> +            = link_to "Sign up", new_developers_path, class: 'mdl-navigation__link'
молодец что разобрался, но исправление в другом месте

у тебя
`resource :developers, only: [:new, :create]`
https://github.com/altvec/task_manager/blob/develop/config/routes.rb#L7

вместо resource в задании было resources. почитай разницу между одиночным и множественным ресурсом

2021-04-27 07:39 UTC, greybutton approved these changes

2021-04-27 09:59 UTC, altvec commented on app/views/layouts/application.html.slim
> +            = link_to "Sign up", new_developers_path, class: 'mdl-navigation__link'
Мда, не увидел. Спасибо, что ткнул носом :) Исправлено.

2021-04-27 10:27 UTC, merged