Feature/assignee selection
altvec/task_manager pull request #20
Opened 2021-05-25 21:42 UTC by altvec

2021-05-27 16:49 UTC, Ensaphelon requested changes

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +  onLoadCard: PropTypes.func.isRequired,
onCardLoad

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/Form/Form.js
> +  const handleChangeSelect = (fieldName) => (user) => onChange({ ...task, [fieldName]: user });
handle{Object}{Action} -> handleSelectChange

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/Form/Form.js
> +  const handleChangeSelect = (fieldName) => (user) => onChange({ ...task, [fieldName]: user });
строка выше - то же самое

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
что будет если убрать 9999? Сломается?

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            getOptionLabel={(user) => UserPresenter.fullName(user)}
getOptionLabel={UserPresenter.fullName}

ниже то же самое

2021-05-27 16:49 UTC, Ensaphelon commented on app/javascript/components/UserSelect/UserSelect.js
> +            onBlur={() => setFocus(false)}
нам обязательно иметь стейт фокуса и управлять им?

2021-05-29 07:23 UTC, altvec commented on app/javascript/components/UserSelect/UserSelect.js
> +            styles={{ menuPortal: (base) => ({ ...base, zIndex: 9999 }) }}
По идее сломается. Выпадающий список будет раскрываться "под" попапом.

2021-05-29 07:23 UTC, altvec commented on app/javascript/components/UserSelect/UserSelect.js
> +            onBlur={() => setFocus(false)}
Если я все правильно понимаю, то нет - не обязательно. Убрал.

2021-06-02 16:46 UTC, greybutton approved these changes

2021-06-02 20:16 UTC, merged